### ISSUE TITLE
[Debian]希望能添加USB网卡的支持(

### ISSUE THREAD

**Issue by cronfox** [OpenStick/OpenStick#1]
如同标题(

**Comment by HandsomeYingyan** [comment]
需要的话自行编译内核吧，在短期内没有更新debian的计划，重新编译内核相关的信息在wiki里面有。

**Comment by cronfox** [comment]
> 需要的话自行编译内核吧，在短期内没有更新debian的计划，重新编译内核相关的信息在wiki里面有。

我先去看看config...

**Comment by cronfox** [comment]
看了下，config里有编译进去，此issue终结

**Comment by cronfox** [comment]
另我这里用的ARM64甲骨文免费机器配Ubuntu容器去编译，不需要设置交叉编译器(
