### ISSUE TITLE
Flash bootloader using edl

### ISSUE THREAD

**Issue by pianojockl** [OpenStick/OpenStick#13]
Hi, thanks for the awesome work!
I seem to have corrupted my stick after it already worked - now I am able to boot into EDL mode, but I'm not sure what I should flash.
Could you advise me how I could recover my stick?

Thank you so much!!

**Comment by sulisu** [comment]
Has the partition table changed? If you bricked it before flash the openstick rom, you can recover it by flash a stock backup rom. 

If you can access pan.baidu.com,

https://pan.baidu.com/s/1-VmcaqiLYNMiaiV73ftOSg
password: u141
(from https://yanziblog.top/291/)

There is a backup of rom for UFIOO1C_MB_V01 in 随身wifi准备工具.zip\UFIOO1C_MB_V01_芷荷_救砖_ROM\UFIOO1C_MB_V01_JZ_ROM\

or you have to find a working stock rom backup by yourself.

Format and flash aboot and system partition, then reboot the stick, it should work now. If it doesn't work, flash all the partition from sbl to system then reboot it. Then you can flash openstick.

If you have flashed openstick, I have not encounted such a situation, but I think you can try to flash partition from base.zip, format all other partition not in base.zip. This will made stick boot into fastboot mode by itself, then you can run flash.bat from debian.zip as normal.

**Comment by pianojockl** [comment]
Wow! Thank you so much for your help!
I was able to flash the stock rom and from there use fastboot to flash debian again! :smile:
