### ISSUE TITLE
how to force fastboot mode with lk2nd

### ISSUE THREAD

**Issue by colemickens** [OpenStick/OpenStick#17]
Hi,

I have the generic-base flashed, but flashed a "bad" rootfs. Do you know how I can force this device into fasboot mode?

I have the board mentioned in this post: https://www.zianet.com/jgray/openstick/08Aug2022.html

I can't figure out how to get it into recovery fastboot mode.

Thanks for any advice.

**Comment by colemickens** [comment]
I've also asked it here: https://forum.openwrt.org/t/qualcomm-msm8916-lte-router-384mib-ram-2-4gib-flash-android-openwrt/131712/33?u=colemickens

**Comment by colemickens** [comment]
alternatively, if you know how to force these boards into EDL, that would be helpful maybe.

**Comment by Informatic** [comment]
edl can be forced by bridging D+ and GND on a USB connector when plugging
it in.

Then, from edl, boot partition can be wiped - this will cause lk2nd to fall
back to fastboot. (According to
https://blog.csdn.net/github_38345754/article/details/121481021 - this was
the behaviour right after flashing base generic image, and before flashing
debian - which only rewrites rootfs and boot partitions)

Make a full backup using edl first in case something goes bad.

**Comment by colemickens** [comment]
I would assume that includes the DP/GND pins on the device itself? No matter what I do, including bridging those pins, I can't seem to see it appear in my `dmesg` so I don't think it's going into EDL.

**Comment by colemickens** [comment]
Hm, well, I also tried making the cable proper and it still didn't seem to work, nothing in dmesg to indicate its picking up a device in EDL mode. :(

**Comment by colemickens** [comment]
from what I could tell observing UART, it just went straight into booting no matter what the 5+ second GND/D+ short. I assume normally it would like pause if those were shorted and then trigger into EDL, but no.

**Comment by Informatic** [comment]
Are you keeping D+ and GND connected when plugging in a USB cable? I am
able to consistently trigger that, but these need to be tied early during
boot/when applying power. This should work, since EDL (iiuc) is implemented
directly in the bootrom... :/

**Comment by colemickens** [comment]
I watched a video on it, I spliced a USB2 extension cable, I'm pinching the black and green wires together for about 5 seconds when I plug it in. But like I said, it just seems to boot straight into lk2nd.

**Comment by colemickens** [comment]
I fried one stick trying various pads and pulling high/low. I have another of this same stick, but same results so far, I can't seem to force it into EDL mode no matter what I try.

**Comment by colemickens** [comment]
I think that @Informatic already knows this, but bridging test pad 1 + 6 while powering on will trigger EDL (test pads counted from the left, with the usb plug on the left, test pads facing up, on the top edge of the board)

This triggers EDL in what seems like bootrom, thereby making this original question moot. (Also, the answer is, patching lk2nd to look for the right GPIO pin for the reset button).
