### ISSUE TITLE
如何关闭4G,USB设定成主机,甚至是CPU降频来节能

### ISSUE THREAD

**Issue by 90999** [OpenStick/OpenStick#2]
如何关闭4G,USB设定成主机,甚至是CPU降频来节能。
这样可以配置成打印机服务器或者插到其他设备上当无线服务器。

**Comment by HandsomeYingyan** [comment]
4g不使用基本上不会明显增加功耗，usb host设置具体参见wiki，cpu降频可以调成powersave模式，这个网上教程挺多的。
