### ISSUE TITLE
firmware-ufi001c.zip 里面没有flash.bat

### ISSUE THREAD

**Issue by jackadam1981** [OpenStick/OpenStick#22]
[firmware-ufi001c.zip](https://github.com/OpenStick/OpenStick/releases/download/v1/firmware-ufi001c.zip)

**Comment by HandsomeYingyan** [comment]
firmware不是靠直接刷入来生效的，所以没有flash脚本。具体怎样操作可以参照readme里的wiki。

**Comment by jackadam1981** [comment]
Windows 下的刷机
作者的windows环境变量里有adb和fastboot，可能需要根据实际情况对脚本进行适当调整。
如果你的设备之前刷过base.zip，则可以将设备置于fastboot模式后从第4步开始。
ufi001b/c之外的版型请使用更为通用的base-generic.zip，然后使用本机型的boot.img替换debian.zip中的boot.img
解压base.zip压缩包。
将你的设备置于fastboot模式
执行其中的flash.bat
当完成后解压<系统名称>.zip压缩包。
执行其中的flash.bat
enjoy!

wiki写的解压  然后flash.bat

**Comment by Hakuin123** [comment]
> 

<系统名称>是Debian吧
