### ISSUE TITLE
如何设置能让WiFi棒子通过局域网访问

### ISSUE THREAD

**Issue by LJ1356** [OpenStick/OpenStick#29]
求教如何使WiFi棒子像树莓派一样通过WiFi连接在 局域网内用ssh访问（局域网内访问）。尝试连接WiFi但是一旦让棒子离开电脑USB口，就无法通过ssh访问，请问是不是要在nmtui界面设置？感谢！

**Comment by openwrt-1983** [comment]
设置联网
输入命令
sudo nmtui

在出现的界面的依次选择
Activate a connection
选择wifi下面的ssid回车
输入ssid的密码回车
看见ssid前面有*就是联网成功

**Comment by LJ1356** [comment]
> 设置联网 输入命令 sudo nmtui
> 
> 在出现的界面的依次选择 Activate a connection 选择wifi下面的ssid回车 输入ssid的密码回车 看见ssid前面有*就是联网成功

感谢。我找到问题原因是无线连接和USB连接的IP地址并不相同，问题已经解决了。

**Comment by HinataKato** [comment]
> > 设置联网 输入命令 sudo nmtui
> > 在出现的界面的依次选择 Activate a connection 选择wifi下面的ssid回车 输入ssid的密码回车 看见ssid前面有*就是联网成功
> 
> 感谢。我找到问题原因是无线连接和USB连接的IP地址并不相同，问题已经解决了。

解决了的话麻烦关一下issue
