### ISSUE TITLE
LTE DeviceNotReady

### ISSUE THREAD

**Issue by kohend** [OpenStick/OpenStick#39]
I flashed the debian image on my stick, got ssh and wifi working, LTE keeps getting errors:
```sudo mmcli -m 0 --simple-connect="apn=uinternet"
[sudo] password for didi: 
error: couldn't connect the modem: 'GDBus.Error:org.freedesktop.libqmi.Error.Protocol.DeviceNotReady: Couldn't set operating mode: QMI protocol error (52): 'DeviceNotReady''
```
With qmicli I'm able to get imsi, but after I do, modem manager doesn't see a modem.
It seems that I have a different model, UFI-7718, or is that just a random number for the original SSID?
Any idea what causes the device not ready issue? Looking over the logs, I didn't see anything apart from it attempting to start, and stop.

**Comment by lyusupov** [comment]
https://github.com/OpenStick/OpenStick/issues/20

**Comment by kohend** [comment]
Thanks, for some reason I didn't find this issue!
