### ISSUE TITLE
关于文档“基础使用”中一些的疑问与建议

### ISSUE THREAD

**Issue by asjdf** [OpenStick/OpenStick#4]
在[《解决debian rndis与wifi热点共存的问题》](https://www.kancloud.cn/handsomehacker/openstick/2684880)中，第三行的注意事项是建议提前连好网，但实际上并不需要如此操作，即使操作错误也可以较为轻松恢复，文中不知道这么操作是有什么考量？

只要利用adb工具就好——系统安装后默认就有adb

同时建议该配网过程直接使用 adb 来进行。

首先将网卡插入电脑 USB 插口，然后在控制台执行`adb shell` ，如报 `adb命令不存在` 等问题，直接找到 adb.exe 所在路径执行 `./adb.exe shell` （有点废话但是还是提一下）

之后操作和原教程一致，可忽略中途检测步骤，全部操作完再检查也行，就算配烂了也不会失去控制。

**Comment by HandsomeYingyan** [comment]
连上网是为了在rndis被调崩的前提下仍然可以通过wifi对设备ssh。adb在某些版本的windows的cmd中运行基于ncurses的nmtui时无法正常显示相应界面，为了教程在不同情况下都能适用，wiki里仍然使用ssh，至少目前大多数的windows下的ssh工具都能正常渲染ncurses。

**Comment by asjdf** [comment]
> 连上网是为了在rndis被调崩的前提下仍然可以通过wifi对设备ssh。adb在某些版本的windows的cmd中运行基于ncurses的nmtui时无法正常显示相应界面，为了教程在不同情况下都能适用，wiki里仍然使用ssh，至少目前大多数的windows下的ssh工具都能正常渲染ncurses。

或许推荐powershell？

**Comment by HandsomeYingyan** [comment]
Powershell上运行的adb在Windows 10 LTSC上貌似还是不能正常渲染，可能在windows上通过ssh是最保险的方案。

**Comment by asjdf** [comment]
> Powershell上运行的adb在Windows 10 LTSC上貌似还是不能正常渲染，可能在windows上通过ssh是最保险的方案。

好的 可能是因为我配过字体
