### ISSUE TITLE
刷base的时候出错了，Warning: skip copying boot image avb footer (boot partition size: 0, boot image size: 342032).

### ISSUE THREAD

**Issue by snapname** [OpenStick/OpenStick#51]
CPU  MSM8916  板子型号： ufi001c_mb_v01
操作系统：windows10 x64专业版
刷入base 的时候出现 Warning: skip copying boot image avb footer (boot partition size: 0, boot image size: 342032). 
忽略继续后面的操作都可以顺利完成，就是刷完不能识别了，（应该是 fastboot flash boot lk2nd.img 的时候出错的）
大佬们这个问题怎么解决哦
![baseScreenshot](https://github.com/OpenStick/OpenStick/assets/29652547/3d2f4234-faa0-4c77-be53-8fd0935ffa32)

**Comment by snapname** [comment]
QualcommPremiumTool查看到的文件 如图
![qcommScreenshot](https://github.com/OpenStick/OpenStick/assets/29652547/3b38a27a-d61e-4ac1-b208-f42adf601da7)

**Comment by woodzn** [comment]
刷回原始固件，重新去刷试试
