### ISSUE TITLE
让WiFi棒子通过Windows的网络共享功能获取网络再由棒子热点转发是否可行。即让WiFi棒子变为外置AP发射器

### ISSUE THREAD

**Issue by Ekilo** [OpenStick/OpenStick#55]

**Comment by ddscentral** [comment]
If you ask whether is possible to use Windows as a gateway and your 4G stick as a WiFi hotspot (not sure how good Google Translate is at translating Chinese), then yes, this is doable.
What you need to do is set modem's RNDIS interface as an ICS target and change modem's USB IP to something from Windows ICS subnet (192.168.137.1/24) and use 192.168.137.1 as the gateway. Your stick should then get internet through Windows.
You will also have to set up your WiFi and routing. I don't want to make this post really long so I won't post detailed instructions. There are tutorials available online on how to configure a Linux router.

**Comment by Ekilo** [comment]
> 如果你问是否有可能使用Windows作为网关，你的4G棒作为WiFi热点（不确定谷歌翻译在翻译中文方面有多好），那么是的，这是可行的。您需要做的是将调制解调器的RNDIS接口设置为ICS目标，并将调制解调器的USB IP更改为Windows ICS子网（192.168.137.1/24）中的某些内容，并使用192.168.137.1作为网关。然后，您的摇杆应该通过Windows上网。您还必须设置您的WiFi和路由。我不想让这篇文章很长，所以我不会发布详细说明。网上有关于如何配置 Linux 路由器的教程。

Thank you for your answer :D
