### ISSUE TITLE
mac电脑通过usb登录到服务器

### ISSUE THREAD

**Issue by macwxx** [OpenStick/OpenStick#6]
参考
https://www.joshuawise.com/horndis
https://github.com/jwise/HoRNDIS
https://github.com/TomHeaven/HoRNDIS
测试因特尔处理器，macOS Mojave 10.14.1 可以正常配置登录，
测试M1 pro处理器，macOS Monterey 12.4  没有配置成功

**Comment by RayPS** [comment]
M1 可以看看这两个：
- https://github.com/jwise/HoRNDIS/issues/135#issuecomment-940140208
- https://github.com/TomHeaven/HoRNDIS/releases/tag/rel9.3_2
