### ISSUE TITLE
怎么安装USB网卡驱动啊，linux小白头疼死了

### ISSUE THREAD

**Issue by Yaklo** [OpenStick/OpenStick#8]
Realtek Semiconductor Corp. RTL8152 Fast Ethernet Adapter

**Comment by HandsomeYingyan** [comment]
编译相应的内核模块就行了，自带了linux-headers，实在不行可以尝试重新编译内核

**Comment by sulisu** [comment]
这两天因为空间不够，打算mount一个samba或nfs共享，发现没有这两个的fs模块，正在学习怎么编译中，不知能否成功。希望有时间方便的话，能够出一个v2版本，包含一些常用的文件系统module，多谢。

**Comment by sulisu** [comment]
https://askubuntu.com/questions/168279/how-do-i-build-a-single-in-tree-kernel-module

这篇文章讲了怎么编译kernel module，一般都不止买一个随身wifi吧，用另外一个装上编译工具编译试试，按作者大神说法header文件都包含了，具备自己在本地编译module的条件。等有时间编译了cifs和nfs的module我把自己的做法放上来。

**Comment by Yaklo** [comment]
> https://askubuntu.com/questions/168279/how-do-i-build-a-single-in-tree-kernel-module
> 
> 这篇文章讲了怎么编译kernel module，一般都不止买一个随身wifi吧，用另外一个装上编译工具编译试试，按作者大神说法header文件都包含了，具备自己在本地编译module的条件。等有时间编译了cifs和nfs的module我把自己的做法放上来。

其实一般人除非搞坏了不然都只会买一个......

**Comment by shum-elli** [comment]
> > https://askubuntu.com/questions/168279/how-do-i-build-a-single-in-tree-kernel-module
> > 这篇文章讲了怎么编译kernel module，一般都不止买一个随身wifi吧，用另外一个装上编译工具编译试试，按作者大神说法header文件都包含了，具备自己在本地编译module的条件。等有时间编译了cifs和nfs的module我把自己的做法放上来。
> 
> 其实一般人除非搞坏了不然都只会买一个......

你好我也遇到了该问题 不过我的网卡型号是亚信的 你是怎么解决的呀
